// const listaProductos = [...new Set(AuxlistaProductos)].map(product => product.trim()).map(target => target === "Ensaladas 4 quesos"? target = "Empanadas 4 quesos":target)
// const auxListaProductos = [
//     'Budín naranja',
//     'Budín chocolate con nuez',
//     'Minon',
//     'Marineras queso',
//     'Churrinches',
//     'Churros',
//     'Donas',
//     'Chipacitos',
//     'Flautas',
//     'Figa chica',
//     'Criollos',
//     'Bizcochos',
//     'Avena naranja',
//     'Figa',
//     'Rosetas',
//     'Bizcochos jamon y queso',
//     'Bolitas',
//     'Flauta',
//     'Minion',
//     'Figasas',
//     'Figasas chicas',
//     'Rocetas',
//     'Criollos',
//     'Medialuna jamon y queso',
//     'Figa salvado',
//     'Bollos salvado',
//     'Pan molde blanco',
//     'Pan molde salvado',
//     'Pre pizza',
//     'Scones fs',
//     'Scon naranja',
//     'Scon chocolate',
//     'Scon pasas uva',
//     'Pameritas',
//     'Empanadas carne',
//     'Empanadas arabe',
//     'Ensaladas 4 quesos',
//     'Empanadas roque',
//     'Minion',
//     'Figasas',
//     'Rocetas',
//     'Criollos (crudos)',
//     'Pre-pizza tomate',
//     'Pan arabe negro',
//     'Pan arabe blanco',
//     'Empanada jyq',
//     'Empanada carne',
//     'Empanada pollo',
//     'Empanada queso tomate jamon',
//     'Pan molde comun',
//     'Bollos negros',
//     'Masas secas ddl',
//     'Bizcochos comunes',
//     'Empanadas arabes',
//     'Minion (sobro)',
//     'Flauta (sobro)',
//     'Budín naranja',
//     'Budín chocolate con nuez',
//     'Minon',
//     'Marineras queso',
//     'Churrinches',
//     'Churros',
//     'Donas',
//     'Chipacitos',
//     'Flautas',
//     'Figa chica',
//     'Criollos',
//     'Bizcochos',
//     'Avena naranja',
//     'Figa',
//     'Rosetas',
//     'Bizcochos jamon y queso',
//     'Bolitas',
//     'Flauta',
//     'Minion',
//     'Figasas',
//     'Figasas chicas',
//     'Rocetas',
//     'Criollos',
//     'Medialuna jamon y queso',
//     'Figa salvado',
//     'Bollos salvado',
//     'Pan molde blanco',
//     'Pan molde salvado',
//     'Pre pizza',
//     'Scones fs',
//     'Scon naranja',
//     'Scon chocolate',
//     'Scon pasas uva',
//     'Pameritas',
//     'Empanadas carne',
//     'Empanadas arabe',
//     'Empanadas 4 quesos',
//     'Empanadas roque',
//     'Minion',
//     'Figasas',
//     'Rocetas',
//     'Criollos (crudos)',
//     'Pre-pizza tomate',
//     'Pan arabe negro',
//     'Pan arabe blanco',
//     'Empanada jyq',
//     'Empanada carne',
//     'Empanada pollo',
//     'Empanada queso tomate jamon',
//     'Pan molde comun',
//     'Bollos negros',
//     'Masas secas ddl',
//     'Bizcochos comunes',
//     'Empanadas arabes',
//     'Minion (sobro)',
//     'Flauta (sobro)',
//     'Rocetas (sobro)',
//     'Medialunas manteca',
//     'Figuras',
//     'Vigilantes',
//     'Medialunas grasa',
//     'Churrinches',
//     'Negritas',
//     'Sacramentos',
//     'Cañoncitos',
//     'Culitos',
//     'Budin limon'
// ]


// for(let i=0 ; i<auxListaProductos.length ; i++ ){
//     if(!auxListaProductos[i].includes(`(sobro)`) && !auxListaProductos[i].includes(`(crudos)`)){
//         ListaProductos.push(auxListaProductos[i])
//     }
    
// }

// ListaProductos.forEach(item=>console.log(`"${item}",`))

export const ListaProductos = [
    "Budín naranja",
    "Budín chocolate con nuez",
    "Minon",
    "Marineras queso",
    "Churrinches",
    "Churros",
    "Donas",
    "Chipacitos",
    "Flautas",
    "Criollos",
    "Bizcochos",
    "Avena naranja",
    "Rosetas",
    "Bizcochos jamon y queso",
    "Bolitas",
    "Flauta",
    "Minion",
    "Figasas",
    "Figasas chicas",
    "Medialuna jamon y queso",
    "Figasas salvado",
    "Bollos salvado",
    "Pan molde blanco",
    "Pan molde salvado",
    "Pre pizza",
    "Scones fs",
    "Scon naranja",
    "Scon chocolate",
    "Scon pasas uva",
    "Pameritas",
    "Empanadas carne",
    "Empanadas arabe",
    "Ensaladas 4 quesos",
    "Empanadas roque",
    "Pre-pizza tomate",
    "Pan arabe negro",
    "Pan arabe blanco",
    "Empanada jyq",
    "Empanada pollo",
    "Empanada queso tomate jamon",
    "Pan molde comun",
    "Masas secas ddl",
    "Bizcochos comunes",
    "Empanadas arabes",
    "Empanadas 4 quesos",
    "Medialunas manteca",
    "Figuras",
    "Vigilantes",
    "Medialunas grasa",
    "Negritas",
    "Sacramentos",
    "Cañoncitos",
    "Culitos",
    "Budin limon",
    "Pepas dulce de leche"
]

// const ListaProductosSinDuplicados = [...new Set(ListaProductos)]